language: csharp
mono: none
dist: xenial
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
osx_image: xcode8.2
script:
  - ./eng/common/cibuild.sh -configuration Release -prepareMachine -integrationTest