name: Ask a question or request support (sponsors and contributors-only)
description: Ask a question about this project or request support
labels: [question]

body:
- type: checkboxes
  attributes:
    label: Confirm you've already contributed to this project or that you sponsor it
    description: "Note: tickets opened by non-sponsors/contributors will be automatically closed."
    options:
    - label: I confirm I'm a sponsor or a contributor
      required: true

- type: input
  id: version
  attributes:
    label: Version
    description: What version of OpenIddict are you running?
  validations:
    required: true

- type: textarea
  attributes:
    label: Question
    description: Your question, including any technical information that may help answer your question.
  validations:
    required: true