<Project Sdk="MSBuild.SDK.SystemWeb">

  <PropertyGroup>
    <TargetFramework>$(NetFrameworkTargetFramework)</TargetFramework>
    <AppConfig>Web.config</AppConfig>
    <GeneratedBindingRedirectsAction>Overwrite</GeneratedBindingRedirectsAction>
    <MvcBuildViews>false</MvcBuildViews>
    <NoWarn>CA3147</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <!--
      Note: Newtonsoft.Json is explicitly referenced to override the
      vulnerable version referenced by other packages or metapackages.
    -->

    <PackageReference Include="Antlr" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Autofac.Mvc5" />
    <PackageReference Include="Autofac.Owin" />
    <PackageReference Include="Microsoft.AspNet.Mvc" />
    <PackageReference Include="Microsoft.AspNet.Web.Optimization" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Owin.Host.SystemWeb" />
    <PackageReference Include="Microsoft.Owin.Security.Cookies" />
    <PackageReference Include="Microsoft.Web.Infrastructure" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="OpenIddict.EntityFramework" />
    <PackageReference Include="OpenIddict.Owin" />
    <PackageReference Include="WebGrease" />
  </ItemGroup>

</Project>